plugins {
    id("java")
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

group = "com.petnuri"
version = "0.0.1-SNAPSHOT"

java {
    sourceCompatibility = '17'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}


dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation 'org.springframework:spring-test:5.3.21'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter'
    // mysql
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // swagger
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    implementation group: 'io.springfox', name: 'springfox-spring-web', version: '3.0.0'
    implementation group: 'io.swagger.core.v3', name: 'swagger-annotations', version: '2.2.21'
    implementation group: 'io.swagger.core.v3', name: 'swagger-models', version: '2.2.21'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    compileOnly group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'
    //시큐리티
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.google.code.gson:gson:2.8.9'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // jjwt 라이브러리 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.11.2'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.2'
    runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.11.2')
    implementation group: 'org.json', name: 'json', version: '20240303'
    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    // firebase
    implementation 'com.google.firebase:firebase-admin:9.2.0'

    //S3
    implementation 'com.amazonaws:aws-java-sdk-s3:1.12.671'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4.1:1.16'  /* Log4JDBC */

    //POI
    implementation 'org.apache.poi:poi-ooxml:5.2.2'
    implementation 'org.apache.poi:poi:5.2.2'

    // HTTP Client for ChatGPT API
    implementation 'com.squareup.okhttp3:okhttp:4.11.0'
    implementation group: 'org.springframework', name: 'spring-web', version: '6.1.4'
    implementation 'org.jsoup:jsoup:1.13.1'

    // PORTONE
    implementation 'com.github.iamport:iamport-rest-client-java:0.2.23'

    implementation 'com.auth0:java-jwt:4.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    implementation 'com.nimbusds:nimbus-jose-jwt:10.4.1' // JWE/JWS

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // MongoDB Starter
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    implementation 'org.springframework.boot:spring-boot-starter-websocket'


}

tasks.test {
    useJUnitPlatform()
}