application:
  version: v0.0.1
  title: RESEARCH2

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.research2.api
  configuration:
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: localhost:9092
    # Kafka 프로듀서/컨슈머 기본 직렬화 설정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: petnuri-app-api
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.petnuri.petnuriappapi.domain.event
        spring.json.value.default.type: com.petnuri.petnuriappapi.domain.event.ShopOrderCreatedEvent
        spring.json.use.type.headers: false



app:
  kafka:
    topics:
      # 주문 생성 이벤트 토픽
      order-created-v1: order-created.v1

  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  consumer:
    group-id: project-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"



